# Auth service specific properties example
#app:
#  enable:
#    security: ${APP_ENABLE_SECURITY:true}
#auth:
#  service:
#    endpoint: ${PERMISSION_SERVICE}
#    get-user-path: /user
#    timeout: 30000
#    error-message: "{\"errorCode\": 401, \"errorMessage\": \"Please authenticate to use this resource!\"}"

#security:
#  urls:
#    open-urls:
#      - /swagger-ui.html
#      - /swagger-ui/**
#      - /swagger-resources/**
#      - /v3/api-docs/**
#      - /favicon.ico
#      - /actuator/**

